# Generated by Django 5.1.1 on 2024-12-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Admin_login',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(default='On Hold', max_length=100)),
            ],
            options={
                'db_table': 'Registration',
            },
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.BigIntegerField()),
                ('names', models.CharField(max_length=300)),
                ('age', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=300)),
                ('ethnicity', models.CharField(max_length=300)),
                ('religion', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=300)),
                ('nationality', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('speecher', models.CharField(max_length=300)),
                ('speech', models.CharField(max_length=300)),
                ('sdate', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'speech',
            },
        ),
    ]
