# Generated by Django 5.1.1 on 2024-12-20 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hate_speech_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech',
            name='userid',
        ),
        migrations.AddField(
            model_name='speech',
            name='score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speech',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hate_speech_app.registration'),
            preserve_default=False,
        ),
    ]
