# Generated by Django 5.1.1 on 2024-12-23 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hate_speech_app', '0002_remove_speech_userid_speech_score_speech_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('age', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=300)),
                ('ethnicity', models.CharField(max_length=300)),
                ('religion', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=300)),
                ('nationality', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('speecher', models.CharField(max_length=300)),
                ('speech', models.CharField(max_length=300)),
                ('sdate', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hate_speech_app.registration')),
            ],
            options={
                'db_table': 'speech_model',
            },
        ),
    ]
