# Generated by Django 5.2.3 on 2025-06-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hate_speech_app', '0004_registration_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='speech',
            field=models.CharField(max_length=500),
        ),
    ]
